# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1859c27bf30b19f0fdf314fa19989aab35b35cfad4626ee965adf682f983ed935b87eea2b0023e690029573536546eab75b3529c63baeb7bb6e5511d5520fd2

test:
  secret_key_base: ec6ddc4693606f168b0ba5f91bac99bfc0f9d31efffc4694cba87580534eb6083c6f2e76b38ed294d9c91acc6bb84939d561fd06e1b39383d29a410baacd09bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
